"""内置示例菜谱（按难度分级，引导备菜台新功能）。"""

EXAMPLE_RECIPES: list[dict] = [
    # ── 简单 ──
    {
        "id": "practice_fried_egg",
        "title": "煎蛋",
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡蛋", "ingredient_id": "egg", "amount_g": 55},
            {"name": "食用油", "ingredient_id": "oil", "amount_g": 8},
            {"name": "食盐", "ingredient_id": "salt", "amount_g": 0.8},
        ],
        "steps": ["热锅下油", "打入鸡蛋，小火定型", "撒盐，出锅"],
        "prep_hints": ["全程小火，油温不要过高。"],
    },
    {
        "id": "practice_rice",
        "title": "蒸米饭",
        "difficulty": "easy",
        "ingredients": [
            {"name": "大米", "ingredient_id": "rice", "amount_g": 150},
            {"name": "水", "ingredient_id": "water", "amount_g": 210},
        ],
        "steps": ["大米淘洗", "加水入锅", "大火烧开转小火焖约15分钟", "关火焖5分钟"],
    },
    {
        "id": "practice_egg_drop_soup",
        "title": "蛋花汤",
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡蛋", "ingredient_id": "egg", "amount_g": 55},
            {"name": "水", "ingredient_id": "water", "amount_g": 500},
            {"name": "盐", "ingredient_id": "salt", "amount_g": 1},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 6},
            {"name": "香油", "ingredient_id": "sesame_oil", "amount_g": 2},
        ],
        "steps": ["水烧开", "淋入蛋液搅成蛋花", "加盐调味，撒葱花淋香油"],
    },
    {
        "id": "practice_garlic_broccoli",
        "title": "蒜蓉西兰花",
        "difficulty": "easy",
        "features": ["prep_board"],
        "ingredients": [
            {"name": "西兰花", "ingredient_id": "broccoli", "amount_g": 250},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 12},
            {"name": "食用油", "ingredient_id": "oil", "amount_g": 10},
            {"name": "盐", "ingredient_id": "salt", "amount_g": 1},
        ],
        "steps": ["西兰花掰小朵", "开水焯30秒捞出备用", "蒜末爆香", "下西兰花快炒调味"],
        "prep_workflow": [
            {"station": "board", "action": "西兰花掰小朵洗净"},
            {"station": "reserve", "action": "焯水后捞出备用，再入锅快炒"},
        ],
    },
    {
        "id": "practice_cucumber_salad",
        "title": "凉拌黄瓜",
        "difficulty": "easy",
        "features": ["prep_board", "seasoning_bowl"],
        "ingredients": [
            {"name": "黄瓜", "ingredient_id": "cucumber", "amount_g": 200},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 8},
            {"name": "醋", "ingredient_id": "vinegar", "amount_g": 10},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 6},
            {"name": "香油", "ingredient_id": "sesame_oil", "amount_g": 3},
            {"name": "盐", "ingredient_id": "salt", "amount_g": 1},
        ],
        "steps": ["黄瓜拍碎切段", "调料碗调匀酱汁", "拌匀装盘"],
        "prep_workflow": [
            {"station": "board", "action": "黄瓜拍碎切段（无需削皮）"},
            {"station": "seasoning", "action": "蒜、醋、生抽、香油、盐调成凉拌汁"},
            {"station": "reserve", "action": "酱汁与黄瓜捞出备用后拌匀入锅/装盘"},
        ],
    },
    {
        "id": "practice_spinach_garlic",
        "title": "蒜蓉菠菜",
        "difficulty": "easy",
        "ingredients": [
            {"name": "菠菜", "ingredient_id": "spinach", "amount_g": 200},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 10},
            {"name": "油", "ingredient_id": "oil", "amount_g": 8},
            {"name": "盐", "ingredient_id": "salt", "amount_g": 1},
        ],
        "steps": ["菠菜洗净", "蒜末爆香", "下菠菜大火快炒", "加盐出锅"],
    },
    # ── 中等 ──
    {
        "id": "practice_tomato_egg",
        "title": "番茄炒蛋",
        "difficulty": "medium",
        "features": ["reserve", "pot_scoop"],
        "ingredients": [
            {"name": "鸡蛋", "ingredient_id": "egg", "amount_g": 110},
            {"name": "番茄", "ingredient_id": "tomato", "amount_g": 220},
            {"name": "食用油", "ingredient_id": "oil", "amount_g": 12},
            {"name": "食盐", "ingredient_id": "salt", "amount_g": 1.2},
            {"name": "白砂糖", "ingredient_id": "sugar", "amount_g": 3},
        ],
        "steps": [
            "鸡蛋炒散盛出备用",
            "番茄切块炒出汁",
            "倒回鸡蛋，加盐、糖炒匀出锅",
        ],
        "prep_hints": ["鸡蛋先炒好「捞出备用」，再炒番茄，最后回锅。"],
    },
    {
        "id": "practice_pepper_pork",
        "title": "青椒肉丝",
        "difficulty": "medium",
        "features": ["prep_board", "marinate", "reserve", "pot_scoop"],
        "ingredients": [
            {"name": "猪肉", "ingredient_id": "pork", "amount_g": 150},
            {"name": "彩椒", "ingredient_id": "bell_pepper", "amount_g": 120},
            {"name": "食用油", "ingredient_id": "oil", "amount_g": 12},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 8},
            {"name": "料酒", "ingredient_id": "cooking_wine", "amount_g": 8},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 6},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 5},
        ],
        "steps": [
            "肉丝滑炒变色盛出备用",
            "青椒切丝下锅断生",
            "回锅肉丝，生抽调味炒匀",
        ],
        "prep_workflow": [
            {"station": "board", "action": "猪肉、彩椒分别切丝"},
            {"station": "marinate", "action": "肉丝+生抽+料酒，腌制15分钟"},
            {"station": "reserve", "action": "腌好肉丝捞出备用"},
            {"station": "pot", "action": "先炒肉丝盛出，再炒青椒，最后合炒"},
        ],
    },
    {
        "id": "practice_potato_shred",
        "title": "酸辣土豆丝",
        "difficulty": "medium",
        "features": ["prep_board"],
        "ingredients": [
            {"name": "土豆", "ingredient_id": "potato", "amount_g": 280},
            {"name": "辣椒", "ingredient_id": "chili", "amount_g": 10},
            {"name": "醋", "ingredient_id": "vinegar", "amount_g": 8},
            {"name": "食用油", "ingredient_id": "oil", "amount_g": 12},
            {"name": "盐", "ingredient_id": "salt", "amount_g": 1},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 8},
        ],
        "steps": [
            "土豆丝泡水去淀粉",
            "热油爆香辣椒",
            "下土豆丝快炒淋醋",
            "撒葱花出锅",
        ],
        "prep_workflow": [
            {"station": "board", "action": "土豆削皮切丝，清水浸泡"},
            {"station": "pot", "action": "大火快炒，出锅前淋醋"},
        ],
    },
    {
        "id": "practice_stir_cabbage",
        "title": "手撕包菜",
        "difficulty": "medium",
        "ingredients": [
            {"name": "卷心菜", "ingredient_id": "cabbage", "amount_g": 300},
            {"name": "猪肉", "ingredient_id": "pork", "amount_g": 60},
            {"name": "干辣椒", "ingredient_id": "chili", "amount_g": 5},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 8},
            {"name": "食用油", "ingredient_id": "oil", "amount_g": 12},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 6},
        ],
        "steps": ["包菜手撕洗净", "热锅炒肉片", "下包菜大火翻炒", "生抽调味出锅"],
        "prep_workflow": [
            {"station": "board", "action": "包菜手撕成片，肉切片"},
        ],
    },
    {
        "id": "practice_cola_chicken",
        "title": "可乐鸡翅",
        "difficulty": "medium",
        "features": ["prep_board", "marinate", "reserve"],
        "ingredients": [
            {"name": "鸡肉", "ingredient_id": "chicken", "amount_g": 280},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 12},
            {"name": "料酒", "ingredient_id": "cooking_wine", "amount_g": 10},
            {"name": "糖", "ingredient_id": "sugar", "amount_g": 15},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 8},
            {"name": "水", "ingredient_id": "water", "amount_g": 80},
            {"name": "油", "ingredient_id": "oil", "amount_g": 8},
        ],
        "steps": [
            "鸡翅煎至两面微黄",
            "加生抽、料酒、糖和水",
            "中火收汁至浓稠",
        ],
        "prep_workflow": [
            {"station": "board", "action": "鸡翅划刀便于入味"},
            {"station": "marinate", "action": "鸡翅+生抽+料酒，腌制30分钟"},
            {"station": "reserve", "action": "腌好捞出备用，再入锅煎制"},
        ],
    },
    {
        "id": "practice_scallion_noodles",
        "title": "葱油拌面",
        "difficulty": "medium",
        "features": ["seasoning_bowl", "reserve"],
        "ingredients": [
            {"name": "面条", "ingredient_id": "noodle", "amount_g": 150},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 40},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 15},
            {"name": "油", "ingredient_id": "oil", "amount_g": 20},
            {"name": "糖", "ingredient_id": "sugar", "amount_g": 3},
        ],
        "steps": [
            "面条煮熟过凉水",
            "小葱切段，油煸至焦香",
            "淋生抽糖汁拌匀面条",
        ],
        "prep_workflow": [
            {"station": "seasoning", "action": "生抽+糖+部分香油调成碗汁"},
            {"station": "pot", "action": "炸葱油后拌面（面条可先捞出备用）"},
        ],
    },
    {
        "id": "practice_three_cup_chicken",
        "title": "三杯鸡",
        "difficulty": "medium",
        "features": ["marinate", "prep_board"],
        "ingredients": [
            {"name": "鸡肉", "ingredient_id": "chicken", "amount_g": 300},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 15},
            {"name": "料酒", "ingredient_id": "cooking_wine", "amount_g": 15},
            {"name": "油", "ingredient_id": "oil", "amount_g": 15},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 10},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 10},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 12},
        ],
        "steps": [
            "鸡块煎至微黄",
            "下姜蒜爆香",
            "加生抽、料酒、油焖至收汁",
            "撒葱段出锅",
        ],
        "prep_workflow": [
            {"station": "board", "action": "鸡肉剁块"},
            {"station": "marinate", "action": "鸡块+料酒，快腌15分钟"},
        ],
    },
    # ── 困难 ──
    {
        "id": "practice_mapo_tofu",
        "title": "麻婆豆腐",
        "difficulty": "hard",
        "features": ["prep_board", "seasoning_bowl", "reserve", "clear_pot"],
        "ingredients": [
            {"name": "豆腐", "ingredient_id": "tofu", "amount_g": 300},
            {"name": "猪肉", "ingredient_id": "pork", "amount_g": 80},
            {"name": "豆瓣酱", "ingredient_id": "bean_paste", "amount_g": 15},
            {"name": "食用油", "ingredient_id": "oil", "amount_g": 12},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 8},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 8},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 6},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 10},
            {"name": "水", "ingredient_id": "water", "amount_g": 80},
            {"name": "淀粉", "ingredient_id": "starch", "amount_g": 5},
        ],
        "steps": [
            "豆腐切块焯水",
            "炒香肉末与豆瓣酱",
            "下豆腐轻推煮入味",
            "勾芡撒葱花出锅",
        ],
        "prep_workflow": [
            {"station": "board", "action": "豆腐切块，肉末剁好"},
            {"station": "seasoning", "action": "豆瓣酱+生抽+淀粉水预备"},
            {"station": "reserve", "action": "焯好豆腐捞出备用，再下锅烧"},
        ],
    },
    {
        "id": "practice_fish_tofu",
        "title": "豆腐烧鱼",
        "difficulty": "hard",
        "features": ["prep_board", "marinate", "reserve"],
        "ingredients": [
            {"name": "鱼肉", "ingredient_id": "fish", "amount_g": 200},
            {"name": "豆腐", "ingredient_id": "tofu", "amount_g": 200},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 8},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 10},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 10},
            {"name": "料酒", "ingredient_id": "cooking_wine", "amount_g": 12},
            {"name": "水", "ingredient_id": "water", "amount_g": 120},
        ],
        "steps": [
            "鱼块煎至两面金黄盛出",
            "下豆腐、姜片",
            "加料酒、生抽、水烧入味",
            "收汁撒葱",
        ],
        "prep_workflow": [
            {"station": "board", "action": "鱼肉切块，豆腐切块"},
            {"station": "marinate", "action": "鱼块+料酒+姜片，腌15分钟"},
            {"station": "reserve", "action": "煎好的鱼块捞出备用，再下豆腐烧制"},
        ],
    },
    {
        "id": "practice_sweet_sour_pork",
        "title": "糖醋里脊",
        "difficulty": "hard",
        "features": ["prep_board", "marinate", "seasoning_bowl", "reserve", "pot_scoop"],
        "ingredients": [
            {"name": "猪肉", "ingredient_id": "pork", "amount_g": 200},
            {"name": "鸡蛋", "ingredient_id": "egg", "amount_g": 55},
            {"name": "淀粉", "ingredient_id": "starch", "amount_g": 25},
            {"name": "糖", "ingredient_id": "sugar", "amount_g": 20},
            {"name": "醋", "ingredient_id": "vinegar", "amount_g": 12},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 6},
            {"name": "油", "ingredient_id": "oil", "amount_g": 25},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 8},
        ],
        "steps": [
            "里脊裹糊下锅炸至金黄盛出",
            "调糖醋汁烧开",
            "倒入炸肉快速裹匀出锅",
        ],
        "prep_workflow": [
            {"station": "board", "action": "里脊切条"},
            {"station": "marinate", "action": "肉条+少许生抽，腌15分钟"},
            {"station": "seasoning", "action": "糖+醋+生抽+水调成糖醋汁"},
            {"station": "reserve", "action": "炸好的里脊捞出备用，再裹汁"},
        ],
    },
    {
        "id": "practice_kungpao_chicken",
        "title": "宫保鸡丁",
        "difficulty": "hard",
        "features": ["prep_board", "marinate", "seasoning_bowl", "reserve", "clear_pot"],
        "ingredients": [
            {"name": "鸡肉", "ingredient_id": "chicken", "amount_g": 200},
            {"name": "干辣椒", "ingredient_id": "chili", "amount_g": 12},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 15},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 6},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 8},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 10},
            {"name": "醋", "ingredient_id": "vinegar", "amount_g": 6},
            {"name": "糖", "ingredient_id": "sugar", "amount_g": 8},
            {"name": "油", "ingredient_id": "oil", "amount_g": 15},
            {"name": "淀粉", "ingredient_id": "starch", "amount_g": 5},
        ],
        "steps": [
            "鸡丁滑炒变色盛出",
            "爆香干辣椒、姜蒜",
            "回锅鸡丁，淋碗汁快炒",
            "撒葱段出锅",
        ],
        "prep_workflow": [
            {"station": "board", "action": "鸡肉切丁，葱切段"},
            {"station": "marinate", "action": "鸡丁+生抽+淀粉，腌15分钟"},
            {"station": "seasoning", "action": "生抽+醋+糖+淀粉水调成宫保汁"},
            {"station": "reserve", "action": "滑炒好的鸡丁捞出，再合炒裹汁"},
        ],
        "prep_hints": ["花生可用胡椒粉代替模拟香脆口感（游戏内简化）。"],
    },
    # ── 挑战 ──
    {
        "id": "practice_braised_pork",
        "title": "红烧肉",
        "difficulty": "expert",
        "features": ["prep_board", "marinate", "reserve", "clear_pot"],
        "ingredients": [
            {"name": "猪肉", "ingredient_id": "pork", "amount_g": 350},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 15},
            {"name": "老抽", "ingredient_id": "dark_soy_sauce", "amount_g": 8},
            {"name": "料酒", "ingredient_id": "cooking_wine", "amount_g": 15},
            {"name": "糖", "ingredient_id": "sugar", "amount_g": 25},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 12},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 15},
            {"name": "水", "ingredient_id": "water", "amount_g": 150},
        ],
        "steps": [
            "五花肉切块焯水",
            "炒糖色下肉块上色",
            "加料酒、生抽、老抽",
            "加水小火焖40分钟",
            "大火收汁",
        ],
        "prep_workflow": [
            {"station": "board", "action": "五花肉切方块"},
            {"station": "marinate", "action": "肉块+料酒+生抽，深腌60分钟"},
            {"station": "reserve", "action": "焯好/腌好的肉捞出备用，再炒糖色焖烧"},
        ],
    },
    {
        "id": "practice_water_boiled_beef",
        "title": "水煮牛肉",
        "difficulty": "expert",
        "features": ["prep_board", "marinate", "seasoning_bowl", "reserve", "clear_pot"],
        "ingredients": [
            {"name": "牛肉", "ingredient_id": "beef", "amount_g": 200},
            {"name": "豆芽", "ingredient_id": "green_bean", "amount_g": 100},
            {"name": "豆瓣酱", "ingredient_id": "bean_paste", "amount_g": 18},
            {"name": "辣椒", "ingredient_id": "chili", "amount_g": 12},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 10},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 8},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 10},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 8},
            {"name": "料酒", "ingredient_id": "cooking_wine", "amount_g": 10},
            {"name": "淀粉", "ingredient_id": "starch", "amount_g": 8},
            {"name": "油", "ingredient_id": "oil", "amount_g": 20},
            {"name": "水", "ingredient_id": "water", "amount_g": 200},
        ],
        "steps": [
            "牛肉切片上浆",
            "底料炒香加水煮开",
            "下蔬菜烫熟垫底",
            "牛肉滑熟铺在菜上",
            "淋热油激香",
        ],
        "prep_workflow": [
            {"station": "board", "action": "牛肉切片，蔬菜洗净"},
            {"station": "marinate", "action": "牛肉+料酒+淀粉，腌30分钟"},
            {"station": "seasoning", "action": "豆瓣酱+辣椒+姜蒜预备底料"},
            {"station": "reserve", "action": "烫熟的蔬菜、滑熟的牛肉分次捞出备用再组装"},
        ],
    },
    {
        "id": "practice_double_pepper_fish",
        "title": "剁椒鱼头（简化版）",
        "difficulty": "expert",
        "features": ["prep_board", "marinate", "seasoning_bowl", "reserve"],
        "ingredients": [
            {"name": "鱼肉", "ingredient_id": "fish", "amount_g": 350},
            {"name": "辣椒", "ingredient_id": "chili", "amount_g": 25},
            {"name": "蒜", "ingredient_id": "garlic", "amount_g": 15},
            {"name": "姜", "ingredient_id": "ginger", "amount_g": 10},
            {"name": "葱", "ingredient_id": "scallion", "amount_g": 12},
            {"name": "生抽", "ingredient_id": "soy_sauce", "amount_g": 10},
            {"name": "料酒", "ingredient_id": "cooking_wine", "amount_g": 12},
            {"name": "油", "ingredient_id": "oil", "amount_g": 15},
            {"name": "水", "ingredient_id": "water", "amount_g": 80},
        ],
        "steps": [
            "鱼头洗净对半劈开",
            "铺剁椒蒜蓉，淋料酒生抽",
            "大火蒸/煮至断生",
            "淋热油撒葱花",
        ],
        "prep_workflow": [
            {"station": "board", "action": "鱼肉处理成大块（模拟鱼头）"},
            {"station": "marinate", "action": "鱼+料酒+姜片，腌20分钟"},
            {"station": "seasoning", "action": "剁椒蒜蓉在调料碗调好"},
            {"station": "reserve", "action": "蒸好的鱼捞出淋油（可先盛出再回锅激香）"},
        ],
    },
]
